dataset_configs:
  desc: Ground Truth Dataset Configurations
  value:
    base_dataset_path: "./dataset/" # LOCAL
    # base_dataset_path: "/content/drive/MyDrive/Programming/dataset/" # GOOGLE COLAB
    cylinder_Re20: "cylinder_Re20_groundtruth.parquet"
    cylinder_Re100: "cylinder_Re100_groundtruth.parquet"
    num_collocation_points: 2000
    num_bc_points: 200
    num_noslip_points: 300
    num_ic_points: 500
    U_mean: 0.2
    domain_bounds:
      x_min: 0.0
      x_max: 2.2
      y_min: 0.0
      y_max: 0.41
      t_min: 0.0
      t_max: 10.0
    steps_per_epoch: 100
    reynolds_number: 20

training_hyperparameters:
  desc: Training Hyperparameters
  value:
    batch_size: 1
    num_epochs: 1000
    learning_rate: 0.001

loss_weights:
  desc: Loss Weights for Different Components
  value:
    lambda_physics: 1.0
    lambda_bc: 1.0
    lambda_ic: 1.0

model_architecture_hyperparameters:
  desc: Model Architecture Hyperparameters
  value:
    hidden_layers: 6
    hidden_width: 64

experiment_details:
  desc: Experiment Details
  value:
    model_dir: "./trained_models/"
    experiment_name: "re20_baseline"
    use_wandb: True

wandb_config:
  desc: Weights and Biases Configuration
  value:
    project: "PINNs_Modeling"
    entity: "deveshshah-university-of-michigan"
    mode: "online"
    config: {}