dataset_configs:
  desc: Ground Truth Dataset Configurations
  value:
    ground_truth_dataset_path: "./dataset/cylinder_Re100_groundtruth.parquet" # LOCAL
    # base_dataset_path: "/content/drive/MyDrive/Programming/dataset/" # GOOGLE COLAB
    num_collocation_points: 12000
    num_near_cylinder_points: 2000
    near_cylinder_radius_factor: 3.0
    num_bc_points: 800
    num_noslip_points: 800
    num_ic_points: 800
    num_data_points: 40000
    U_mean: 1.0
    domain_bounds:
      x_min: 0.0
      x_max: 2.2
      y_min: 0.0
      y_max: 0.41
      t_min: 0.0
      t_max: 8.0
    cylinder_geometry:
      cx: 0.2
      cy: 0.2
      r: 0.05
    steps_per_epoch: 100
    reynolds_number: 100
    nu: 0.001 # kinematic viscosity nu = U_mean * D / Re, where D=0.1m U_mean=1.0m/s Re=100

training_hyperparameters:
  desc: Training Hyperparameters
  value:
    batch_size: 1
    num_epochs: 2000
    learning_rate: 0.002

loss_weights:
  desc: Loss Weights for Different Components
  value:
    lambda_physics: 3.0
    lambda_bc: 5.0
    lambda_ic: 3.0
    lambda_data: 2.0

model_architecture_hyperparameters:
  desc: Model Architecture Hyperparameters
  value:
    hidden_layers: 6
    hidden_width: 128

experiment_details:
  desc: Experiment Details
  value:
    model_dir: "./trained_models/"
    experiment_name: "re100_withSup_FF"
    use_wandb: True

wandb_config:
  desc: Weights and Biases Configuration
  value:
    project: "PINNs_Modeling"
    entity: "deveshshah-university-of-michigan"
    mode: "online"
    config: {}